name: Ping MongoDB

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run ping script
        run: node pingMongo.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

